### PR TITLE
Fix JWT Security Validator issue in .NET

### LINKED ISSUE #260: Blazor .NET 8 Error
### Describe the bug?

After updating to 4.6, my Blazor app is failing to authenticate.
Can reproduce with .NET 6 Sample code (after upgrading to .NET 8)

### What is expected to happen?

Authentication

### What is the actual behavior?

An unhandled exception occurred while processing the request.
SecurityTokenException: The Validated Security Token must be of type JsonWebToken, but instead its type is 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateTokenUsingHandlerAsync(string idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters)

AuthenticationFailureException: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

### Reproduction Steps?

Pull https://github.com/okta/samples-blazor, use Upgrade Assistant to move the demo to .NET 8.
Update Appsettings to working API keys
Test - All works
Update NuGet package Okta.AspNetCore to 4.6.0
Test - Above Error show

### Additional Information?

_No response_

### .NET Version

8.0.200

### SDK Version

4.6

### OS version

BuildNumber  Caption                          OSArchitecture  Version
22631        Microsoft Windows 11 Enterprise  64-bit          10.0.22631

### PR DESCRIPTION
**Pull request by laura-rodriguez**
- Upgrade vuln dependencies (System.IdentityModel.Tokens.Jwt to 6.35)
- Add oidcOptions.UseSecurityTokenValidator = true setting for .NET 8 projects to keep using JwtSecurityToken (https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/securitytoken-events)
- Add .NET8 as a valid frameworkTarget for Okta.AspNet.Abstractions
- Update updated project's version in prep for an upcoming release
- Fix #260 #261 #259

### CODE REVIEW

File: Okta.AspNetCore/OpenIdConnectOptionsHelper.cs [hunk 1]
```diff
@@ -37,7 +37,9 @@ public static void ConfigureOpenIdConnectOptions(OktaMvcOptions oktaMvcOptions,
             oidcOptions.SignedOutRedirectUri = oktaMvcOptions.PostLogoutRedirectUri;
             oidcOptions.ResponseType = OpenIdConnectResponseType.Code;
             oidcOptions.GetClaimsFromUserInfoEndpoint = oktaMvcOptions.GetClaimsFromUserInfoEndpoint;
+
 #if NET8_0_OR_GREATER
+            oidcOptions.UseSecurityTokenValidator = true;
             oidcOptions.TokenHandler = new StrictTokenHandler();
```
Comment (NickDrouin) [inline Okta.AspNetCore/OpenIdConnectOptionsHelper.cs:43]: @laura-rodriguez , thank you for looking into this.

In my work-around in #260 : 
I continue to use the Okta-supplied validation path, by explicitly calling it -- much like the dot-net code would have if `UseSecurityTokenValidator==false`.

A second validation is then done by dotnet because I set `UseSecurityTokenValidator=true`.

I believe that setting `oidcOptions.UseSecurityTokenValidator = true;` here, the dotnet code will never call the Okta-supplied `StrictTokenHandler` because it will never call `ValidateTokenUsingHandlerAsync` within OpenIdConnectHandler.cs#L532.

Can you confirm that it is desired by Okta, when running in net8.0, that only the default dotnet validator is used.?

If so, then the line `oidcOptions.TokenHandler = new StrictTokenHandler();` is not needed here as it is never called.
Otherwise, another approach will be needed.

**Review by NickDrouin — COMMENTED** [review]
See open question : is the intent to fully-deprecate the use of Okta's `StrictTokenHandler`?

File: Okta.AspNetCore/OpenIdConnectOptionsHelper.cs (hunk 1 above)
Comment (laura-rodriguez) [reply Okta.AspNetCore/OpenIdConnectOptionsHelper.cs:43]: Hi @NickDrouin,

Excellent point. You're right; I'll be pushing an update soon.

Thank you

Comment (GeoRHeld) [reply Okta.AspNetCore/OpenIdConnectOptionsHelper.cs]: Agree with @NickDrouin that setting UseSecurityTokenValidator to true will never call any of the Okta custom handlers as nothing was ever set for the SecurityTokenValidator property.

IMHO, To make this library NET8.0 compliant, a new class should be added to handle token validation for the JsonWebToken type.  This new class would be derived from the JsonWebTokenHandler class and then assigned to the TokenHandler property on the oidcOptions.  This new class would override the ValidateToken and ValidateTokenAsync methods to add additional validation for the RS256 algorithm requirement, similar to the existing StrictTokenHandler class.

Comment (laura-rodriguez) [reply Okta.AspNetCore/OpenIdConnectOptionsHelper.cs]: Hey @GeoRHeld,

Thank you for your feedback. Due to timeline concerns and to unblock our customers as soon as possible, we'll patch this release using the `UseSecurityTokenValidator` setting. I'll file a follow-up internal ticket to be fully .NET 8 compliant and add all the necessary testing to ensure everything's working as expected.

**Comment by laura-rodriguez** [comment]
Hi everyone,

I've attached the temp artifacts for you to look over if you want to test locally.

Thank you all!

[artifacts.RC1.zip](https://github.com/okta/okta-aspnet/files/15001301/artifacts.RC1.zip)

**Review by GeoRHeld — APPROVED** [review]
Works for me.

**Review by bryanapellanes-okta — APPROVED** [review]
👍

**Comment by NickDrouin** [comment]
@laura-rodriguez : what is the issue / tracking number of the feature that will restore the Okta `StrictTokenHandler` ?
Or, has Okta taken the design decision to deprecate it in favor of the base security token validator?

What is the roadmap to moving towards the JsonWebToken ?

[Copied to bug thread.]
